Added ElementExtensions
windows-toolkit/Graph-Controls pull request #106
Opened 2021-05-27 23:04 UTC by shweaver-MSFT

Fixes #9 and #97

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the new behavior?

You can now toggle visibility for elements based on the current provider state:

```
<TextBlock wgt:ElementExtensions.IsVisibleWhenSignedIn="True" Text="Only visible when signed in" />
<TextBlock wgt:ElementExtensions.IsVisibleWhenSignedIn="False" Text="Only visible when not signed in (Loading or SignedOut)" />
<TextBlock wgt:ElementExtensions.IsVisibleWhenSignedIn="null" Text="Default visibility" />
```

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](https://github.com/windows-toolkit/Graph-Controls/blob/main/README.md)
- [ ] Sample in sample app has been added / updated (for bug fixes / features)
  - [ ] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/windows-toolkit/WindowsCommunityToolkit-design-assets)
- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Header has been added to all new source files (run _build/UpdateHeaders.bat_)
- [ ] Contains **NO** breaking changes

## Other information

2021-06-01 20:25 UTC, michael-hawker requested changes

2021-06-01 20:25 UTC, michael-hawker commented on CommunityToolkit.Graph.Uwp/Extensions/ElementExtensions.cs
> +        private static readonly IList<FrameworkElement> _listeningElements = new List<FrameworkElement>();
Wondering if we want a `ConcurrentDictionary` would be a tiny bit safer here? ([reference for another use case in the Toolkit already](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/63cbb4a51bdef59083ccfc86bbcba41f966d0027/Microsoft.Toolkit.Uwp/Extensions/DispatcherQueueTimerExtensions.cs#L16))

2021-06-01 20:25 UTC, michael-hawker commented on CommunityToolkit.Graph.Uwp/Extensions/ElementExtensions.cs
> +    public class ElementExtensions : DependencyObject
Think this could be static as well? See what we do for other extensions/helpers in the Toolkit?

2021-06-01 20:25 UTC, michael-hawker commented on CommunityToolkit.Graph.Uwp/Extensions/ElementExtensions.cs
> +            foreach (var element in _listeningElements)
Think we'd want to lock around iterating over the collection and the add/remove elements from the other properties?

2021-06-02 00:07 UTC, shweaver-MSFT commented
Thanks for the feedback @michael-hawker :) 

Thinking about naming as well since it is a bit verbose... What do you think about:

```
<TextBlock wgt:ProviderExtensions.IsVisibleWhen="SignedIn" Text="Only visible when signed in" />
<TextBlock wgt:ProviderExtensions.IsVisibleWhen="SignedOut" Text="Only visible when signed out" />
<TextBlock wgt:ProviderExtensions.IsVisibleWhen="Loading" Text="You get the picture" />
```

`CommunityToolkit.Graph.Uwp.ProviderExtensions` is a bit funny naming, since it wouldn't be the same as the existing `CommunityToolkit.Graph.ProviderExtensions`. But I don't know if that is necessarily a bad thing... They are both static and will likely never be used in the same context (XAML vs in code).

Thoughts? What do you think @nmetulev?

2021-06-11 17:45 UTC, merged